"""requisite table

Revision ID: 20121434709c
Revises: c2e4b646c670
Create Date: 2024-12-01 14:03:33.800817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20121434709c'
down_revision: Union[str, None] = 'c2e4b646c670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('card', 'crypto', name='requisite_type').create(op.get_bind())
    op.create_table('requisites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', postgresql.ENUM('card', 'crypto', name='requisite_type', create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisites')
    sa.Enum('card', 'crypto', name='requisite_type').drop(op.get_bind())
    # ### end Alembic commands ###
