"""purchase request

Revision ID: f64bd8457d8c
Revises: 60b10c34c003
Create Date: 2024-10-19 17:44:09.936996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64bd8457d8c'
down_revision: Union[str, None] = '60b10c34c003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('purchase_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('withdraw_commission', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('transfer_commission', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('product_commission', sa.DECIMAL(), nullable=True))
    op.drop_column('user', 'commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('commission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'product_commission')
    op.drop_column('user', 'transfer_commission')
    op.drop_column('user', 'withdraw_commission')
    op.drop_table('purchase_request')
    # ### end Alembic commands ###
