"""withdraw method

Revision ID: 4e9237a4f9f4
Revises: 0438cc20e328
Create Date: 2024-09-29 07:55:08.824687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9237a4f9f4'
down_revision: Union[str, None] = '0438cc20e328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdraw_method',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_holder_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['withdraw_method.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_address', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['withdraw_method.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_details')
    op.drop_table('crypto_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crypto_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='crypto_details_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='crypto_details_pkey')
    )
    op.create_table('card_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='card_details_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='card_details_pkey')
    )
    op.drop_table('crypto_method')
    op.drop_table('card_method')
    op.drop_table('withdraw_method')
    # ### end Alembic commands ###
