"""invoice url nullable

Revision ID: b143839ce2ed
Revises: 60c0060e3da2
Create Date: 2024-12-07 21:11:50.845396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b143839ce2ed'
down_revision: Union[str, None] = '60c0060e3da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'invoice_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'invoice_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
