"""empty message

Revision ID: 5ae3764f8e91
Revises: 
Create Date: 2024-10-16 19:38:02.992070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae3764f8e91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=True),
    sa.Column('total_withdrawn', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_receipt', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Enum('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PROCESSING', 'COMPLETE', 'CANCEL', 'DELAY', name='order_status'), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'id', name='uq_type_id')
    )
    op.create_table('user_topic',
    sa.Column('thread_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('supergroup_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('completed_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('paypal_received_amount', sa.DECIMAL(), nullable=False),
    sa.Column('user_received_amount', sa.DECIMAL(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digital_product_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), nullable=False),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['type'], ['order.type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), nullable=False),
    sa.Column('receiver_email', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('receipt_photo_url', sa.String(), nullable=False),
    sa.Column('commission', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['type'], ['order.type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdraw_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), nullable=False),
    sa.Column('payment_receipt', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'CRYPTO', name='method_enum'), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('card_holder_name', sa.String(), nullable=True),
    sa.Column('crypto_address', sa.String(), nullable=True),
    sa.Column('crypto_network', sa.String(), nullable=True),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['type'], ['order.type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdraw_details')
    op.drop_table('transfer_details')
    op.drop_table('digital_product_details')
    op.drop_table('completed_order')
    op.drop_table('user_topic')
    op.drop_table('order')
    op.drop_table('feedback')
    op.drop_table('user')
    # ### end Alembic commands ###
