"""add sequence for web_place

Revision ID: fc9e217f37ed
Revises: d7c80d080136
Create Date: 2024-11-04 18:32:16.620541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9e217f37ed'
down_revision: Union[str, None] = 'd7c80d080136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE web_place_seq START 1")
    op.alter_column('platform', 'web_place', existing_type=sa.Integer(), nullable=False, server_default=sa.text('nextval(\'web_place_seq\'::regclass)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
