"""add completed_order table

Revision ID: fbc7d2da5c94
Revises: 1aa2b972ce7a
Create Date: 2024-08-28 17:37:02.769235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbc7d2da5c94'
down_revision: Union[str, None] = '1aa2b972ce7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('paypal_received_amount', sa.DECIMAL(), nullable=False),
    sa.Column('user_received_amount', sa.DECIMAL(), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('taken_commission', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('order', 'final_amount')
    op.drop_column('order', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('final_amount', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('order', 'created_at')
    op.drop_table('completed_order')
    # ### end Alembic commands ###
