"""card number length

Revision ID: 8b8c8926e9a5
Revises: 8ad1ab7e5964
Create Date: 2024-12-01 17:34:33.629859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8c8926e9a5'
down_revision: Union[str, None] = '8ad1ab7e5964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_requisite', 'number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=19),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_requisite', 'number',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
