"""add timestampts

Revision ID: 1aa2b972ce7a
Revises: d02a3ccf0b7f
Create Date: 2024-08-27 18:37:27.524683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aa2b972ce7a'
down_revision: Union[str, None] = 'd02a3ccf0b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('order', 'withdrawal_detail')
    op.add_column('user', sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('commission', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total_withdrawn', sa.DECIMAL(), nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'joining_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joining_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'total_withdrawn')
    op.drop_column('user', 'commission')
    op.drop_column('user', 'joined_at')
    op.add_column('order', sa.Column('withdrawal_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('feedback')
    # ### end Alembic commands ###
