"""empty message

Revision ID: 5b4f54ba69e1
Revises: 8dcbd8985c64
Create Date: 2024-09-11 16:17:07.415221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4f54ba69e1'
down_revision: Union[str, None] = '8dcbd8985c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'telegram_message_id')
    # ### end Alembic commands ###
