"""empty message

Revision ID: 60b10c34c003
Revises: 5dd5338a22b1
Create Date: 2024-10-19 10:31:26.776710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b10c34c003'
down_revision: Union[str, None] = '5dd5338a22b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_order', 'paypal_received_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('completed_order', 'user_received_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_order', 'user_received_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('completed_order', 'paypal_received_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
