"""strenum to enum status

Revision ID: e35c42f16987
Revises: 77675e53e4d3
Create Date: 2024-12-15 13:48:47.984253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = 'e35c42f16987'
down_revision: Union[str, None] = '77675e53e4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public', 
        enum_name='order_status', 
        new_values=['NOT_PAID', 'COMPLETE', 'CANCEL', 'PROCESSING', 'NEW', 'DELAY'], 
        affected_columns=[TableReference(table_schema='public', table_name='order', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
