"""empty message

Revision ID: f3424296a4e1
Revises: 9bc855427b2c
Create Date: 2024-11-01 11:19:39.388799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3424296a4e1'
down_revision: Union[str, None] = '9bc855427b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'withdraw_commission')
    op.drop_column('user', 'transfer_commission')
    op.drop_column('user', 'product_commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('product_commission', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('transfer_commission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('withdraw_commission', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
