"""add name column

Revision ID: d7c80d080136
Revises: 14af1df9f373
Create Date: 2024-11-02 17:56:28.539679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c80d080136'
down_revision: Union[str, None] = '14af1df9f373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('purchase_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('instruction', sa.String(length=500), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('platform_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instruction', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='platform_service_platform_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='platform_service_pkey')
    )
    op.drop_table('platform_product')
    # ### end Alembic commands ###
