"""login data

Revision ID: bd7a3f0c25b5
Revises: f3424296a4e1
Create Date: 2024-11-01 19:43:39.774574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd7a3f0c25b5'
down_revision: Union[str, None] = 'f3424296a4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_product_details', sa.Column('login_data', sa.JSON(), nullable=True))
    op.add_column('product_application', sa.Column('login_data', sa.JSON(), nullable=True, server_default=None))
    op.drop_column('product_application', 'required_fields')
    op.sync_enum_values('public', 'product_application_status', ['SENT', 'FULFILLED'],
                        [TableReference(table_schema='public', table_name='product_application', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'product_application_status', ['SENT', 'FULLFILLED'],
                        [TableReference(table_schema='public', table_name='product_application', column_name='status')],
                        enum_values_to_rename=[])
    op.add_column('product_application', sa.Column('required_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('product_application', 'login_data')
    op.drop_column('digital_product_details', 'login_data')
    # ### end Alembic commands ###
