"""add status to request

Revision ID: 1e6aa6066b01
Revises: f64bd8457d8c
Create Date: 2024-10-19 20:23:03.935194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import alembic_postgresql_enum

from src.infrastructure.data.models import Base

# revision identifiers, used by Alembic.
revision: str = '1e6aa6066b01'
down_revision: Union[str, None] = 'f64bd8457d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_status = sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='request_status', metadata=Base.metadata)

def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    new_status.create(op.get_bind(), checkfirst=True)
    op.add_column('purchase_request', sa.Column('status', new_status, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_request', 'status')
    # ### end Alembic commands ###
