"""product_application

Revision ID: 08b9384dac76
Revises: 1e6aa6066b01
Create Date: 2024-10-19 23:36:08.292486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08b9384dac76'
down_revision: Union[str, None] = '1e6aa6066b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SENT', 'FULLFILLED', name='product_application_status').create(op.get_bind())
    op.create_table('product_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'FULLFILLED', name='product_application_status', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.sync_enum_values('public', 'request_status', ['PENDING', 'CONFIRMED', 'CANCELLED'],
                        [TableReference(table_schema='public', table_name='purchase_request', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'request_status', ['PENDING', 'COFIRMED', 'CANCELLED'],
                        [TableReference(table_schema='public', table_name='purchase_request', column_name='status')],
                        enum_values_to_rename=[])
    op.drop_table('product_application')
    sa.Enum('SENT', 'FULLFILLED', name='product_application_status').drop(op.get_bind())
    # ### end Alembic commands ###
