"""order commission

Revision ID: 938b7ad0f4b4
Revises: 63fab15bcb00
Create Date: 2024-10-06 09:18:19.038625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938b7ad0f4b4'
down_revision: Union[str, None] = '63fab15bcb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('commission', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'commission')
    # ### end Alembic commands ###
