"""withdraw dtails add requisite id

Revision ID: 1bc0e78d95e0
Revises: 8b8c8926e9a5
Create Date: 2024-12-04 18:20:27.946929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bc0e78d95e0'
down_revision: Union[str, None] = '8b8c8926e9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw_details', sa.Column('requisite_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'withdraw_details', 'requisite', ['requisite_id'], ['id'], ondelete='SET NULL')
    op.drop_column('withdraw_details', 'crypto_network')
    op.drop_column('withdraw_details', 'crypto_address')
    op.drop_column('withdraw_details', 'card_number')
    op.drop_column('withdraw_details', 'card_holder_name')
    op.drop_column('withdraw_details', 'method')
    sa.Enum('CARD', 'CRYPTO', name='method_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CARD', 'CRYPTO', name='method_enum').create(op.get_bind())
    op.add_column('withdraw_details', sa.Column('method', postgresql.ENUM('CARD', 'CRYPTO', name='method_enum', create_type=False), autoincrement=False, nullable=False))
    op.add_column('withdraw_details', sa.Column('card_holder_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('withdraw_details', sa.Column('card_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('withdraw_details', sa.Column('crypto_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('withdraw_details', sa.Column('crypto_network', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'withdraw_details', type_='foreignkey')
    op.drop_column('withdraw_details', 'requisite_id')
    # ### end Alembic commands ###
