"""feedback photo

Revision ID: c2e4b646c670
Revises: f5c025633f6d
Create Date: 2024-11-28 15:17:11.113384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e4b646c670'
down_revision: Union[str, None] = 'f5c025633f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('photo', sa.JSON(), nullable=True))
    op.drop_column('feedback', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('feedback', 'photo')
    # ### end Alembic commands ###
