"""user commission

Revision ID: 4f8d1b9a7e69
Revises: 60b10c34c003
Create Date: 2024-10-31 19:07:43.340654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8d1b9a7e69'
down_revision: Union[str, None] = '60b10c34c003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_commission',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transfer', sa.DECIMAL(), nullable=False),
    sa.Column('withdraw', sa.DECIMAL(), nullable=False),
    sa.Column('digital_product', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('completed_order', sa.Column('payment_system_received_amount', sa.DECIMAL(), nullable=True))
    op.drop_column('completed_order', 'paypal_received_amount')
    # op.drop_column('user', 'commission')
    op.alter_column('withdraw_details', 'commission',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdraw_details', 'commission',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('user', sa.Column('commission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('completed_order', sa.Column('paypal_received_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('completed_order', 'payment_system_received_amount')
    op.drop_table('user_commission')
    # ### end Alembic commands ###
