"""payment receipt to nullable

Revision ID: 77675e53e4d3
Revises: b143839ce2ed
Create Date: 2024-12-15 13:37:48.010688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77675e53e4d3'
down_revision: Union[str, None] = 'b143839ce2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_details', 'receipt_photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_details', 'receipt_photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
