"""empty message

Revision ID: 5c3fb5a884f9
Revises: 938b7ad0f4b4
Create Date: 2024-10-09 19:54:35.263317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c3fb5a884f9'
down_revision: Union[str, None] = '938b7ad0f4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_order', sa.Column('completed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('completed_order', 'received_at')
    op.drop_column('completed_order', 'taken_commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_order', sa.Column('taken_commission', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('completed_order', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('completed_order', 'completed_at')
    # ### end Alembic commands ###
