"""empty message

Revision ID: 5dd5338a22b1
Revises: 5ae3764f8e91
Create Date: 2024-10-16 20:15:51.310428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd5338a22b1'
down_revision: Union[str, None] = '5ae3764f8e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_product_details', 'id')
    op.drop_column('digital_product_details', 'type')
    op.drop_column('transfer_details', 'id')
    op.drop_column('transfer_details', 'type')
    op.drop_column('withdraw_details', 'id')
    op.drop_column('withdraw_details', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw_details', sa.Column('type', postgresql.ENUM('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), autoincrement=False, nullable=False))
    op.add_column('withdraw_details', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('transfer_details', sa.Column('type', postgresql.ENUM('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), autoincrement=False, nullable=False))
    op.add_column('transfer_details', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('digital_product_details', sa.Column('type', postgresql.ENUM('WITHDRAW', 'TRANSFER', 'DIGITAL_PRODUCT', name='order_type'), autoincrement=False, nullable=False))
    op.add_column('digital_product_details', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
