"""requisite_id to nullable

Revision ID: cf854fdbf70b
Revises: 1bc0e78d95e0
Create Date: 2024-12-07 15:53:08.688109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf854fdbf70b'
down_revision: Union[str, None] = '1bc0e78d95e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdraw_details', 'requisite_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdraw_details', 'requisite_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
