"""add feedback photo url

Revision ID: 3a5ce86bb2eb
Revises: 5c3fb5a884f9
Create Date: 2024-10-13 19:16:44.406443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5ce86bb2eb'
down_revision: Union[str, None] = '5c3fb5a884f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('completed_order', 'order_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    op.add_column('feedback', sa.Column('photo_url', sa.String(), nullable=True))
    # op.alter_column('order', 'id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=False,
    #            autoincrement=False,
    #            existing_server_default=sa.text("nextval('order_id_seq'::regclass)"))
    # op.alter_column('withdraw_method', 'order_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdraw_method', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('order', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=False,
               existing_server_default=sa.text("nextval('order_id_seq'::regclass)"))
    op.drop_column('feedback', 'photo_url')
    op.alter_column('completed_order', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
