"""add tg message id

Revision ID: d512d5d83361
Revises: 08b9384dac76
Create Date: 2024-10-20 00:31:59.336783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd512d5d83361'
down_revision: Union[str, None] = '08b9384dac76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_request', sa.Column('telegram_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_request', 'telegram_message_id')
    # ### end Alembic commands ###
