"""withdraw method

Revision ID: ac2b22096005
Revises: 4e9237a4f9f4
Create Date: 2024-10-05 18:58:43.931852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2b22096005'
down_revision: Union[str, None] = '4e9237a4f9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_method')
    op.drop_table('crypto_method')
    op.add_column('withdraw_method', sa.Column('card_number', sa.String(length=16), nullable=True))
    op.add_column('withdraw_method', sa.Column('card_holder_name', sa.String(), nullable=True))
    op.add_column('withdraw_method', sa.Column('crypto_address', sa.String(), nullable=True))
    op.add_column('withdraw_method', sa.Column('crypto_network', sa.String(), nullable=True))
    
    # Create the enum type
    op.execute("CREATE TYPE method_enum AS ENUM ('CARD', 'CRYPTO')")
    
    # Alter the column type with USING clause
    op.execute("ALTER TABLE withdraw_method ALTER COLUMN method TYPE method_enum USING method::method_enum")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdraw_method', 'method',
               existing_type=sa.Enum('CARD', 'CRYPTO', name='methodenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('withdraw_method', 'crypto_network')
    op.drop_column('withdraw_method', 'crypto_address')
    op.drop_column('withdraw_method', 'card_holder_name')
    op.drop_column('withdraw_method', 'card_number')
    op.create_table('crypto_method',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crypto_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['withdraw_method.id'], name='crypto_method_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='crypto_method_pkey')
    )
    op.create_table('card_method',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_holder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['withdraw_method.id'], name='card_method_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='card_method_pkey')
    )
    # ### end Alembic commands ###
