[commission]
digital_product = 5
[commission.paypal]
min-withdraw-percentage = 5
max-withdraw-percentage = 13
min-withdraw-usd-amount = 20
max-withdraw-usd-amount = -1
max-transfer-amount = 2000
max-transfer-percentage = 13
min-transfer-percentage = 5

[commission.digital-product]
usd-amount-commission = 5

[yandex-cloud]
base-storage-url = 'https://storage.yandexcloud.net'
receipts-bucket-name = 'overseas-pay-receipts'
feedbacks-bucket-name = 'overseas-pay-feedbacks'
platforms-bucket-name = 'overseaspay-platforms'
products-bucket-name = 'overseas-pay-products'
yandex-access-key-id = 'YCAJE0myJzwMRGXSKyLNelnrx'
yandex-access-secret-key = 'YCN2tGHqL5ozoIUmaWFbHPICSjS4cBO1Xm1jaj_a'

[web]
post-feedback-url = 'https://seaspayment.com/feedbacks/post'