[commission]
digital_product = 5
[commission.paypal]
min_percentage_to_withdraw = 7
max_percentage_to_withdraw = 15
min_amount_to_withdraw = 10
max_amount_to_withdraw = "UNLIMITED"
max_amount_to_transfer = 3000
commission_to_transfer = 5

[yandex-cloud]
base-storage-url = 'https://storage.yandexcloud.net'
receipts-bucket-name = 'overseas-pay-receipts'
feedbacks-bucket-name = 'overseas-pay-feedbacks'
yandex-access-key-id = 'YCAJE0myJzwMRGXSKyLNelnrx'
yandex-access-secret-key = 'YCN2tGHqL5ozoIUmaWFbHPICSjS4cBO1Xm1jaj_a'